services:
  directus:
    image: directus/directus:latest
    restart: always
    container_name: directus
    ports:
      - 8055:8055
    env_file:
      - .env.docker
    depends_on:
      - postgres
    volumes:
      - directus-uploads:/directus/uploads
      - directus-extensions:/directus/extensions

  postgres:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env.docker
    volumes:
      - directus-postgres-data:/var/lib/postgresql/data

volumes:
  directus-uploads:
  directus-extensions:
  directus-postgres-data:
